version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "movie-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6a5eir1vgmpd"
s3_prefix = "movie-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
